apiVersion: v1
kind: Pod
metadata:
  name: jhunt
spec:
  containers:
    - name: jumpbox
      image: huntprod/jumpbox:jhunt
      imagePullPolicy: Always
      command: ['/bin/sleep']
      args: ['10000d']
