---
apiVersion: v1
kind: Namespace
metadata:
  name: jumpboxen
---
apiVersion: v1
kind: Pod
metadata:
  name: jhunt
  namespace: jumpboxen
spec:
  containers:
    - name: jumpbox
      image: huntprod/jumpbox:jhunt
      imagePullPolicy: Always
      command: [pause]
